FROM node
MAINTAINER Tobias Freundorfer, https://github.com/tfreundo

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git && \
    apt-get install -y netcat

# Install nodeunit project globally
RUN npm --quiet install -g nodeunit

# Add user
RUN useradd -ms /bin/bash tester

USER tester
WORKDIR /home/tester

# Clone APIAdapter repo
RUN git clone -b dev-swagger https://github.com/tfreundo/gRPC-APIAdapter.git

# Install all necessary modules using npm
RUN export NODE_PATH=$NODEPATH:/home/tester/gRPC-APIAdapter/rest-tester/testgrpcapi
WORKDIR /home/tester/gRPC-APIAdapter/rest-tester/testgrpcapi
RUN npm --quiet install
