version: '2'
services:

  testgrpc:
    build:
      context: .
      dockerfile: TODO
    ports:
      - "8181:8181"
    volumes:
      - apistore:/api
    command: TODO

  restapiadapter:
    build:
      context: .
      dockerfile: Dockerfile-restapiadapter
    volumes_from:
      - testgrpc
    links:
      - testgrpc
    ports:
      - "8080:8080"
    # This only affects runtime!!! Need to duplicate in Dockerfile if needed at buildtime!!
    environment:
      API_HOST: testgrpc
      API_PORT: 8181
      API_PROTO_PATH: /api/main.proto
      REST_HOST: "0.0.0.0"
      REST_PORT: 8080
    command: ./startRESTApi.sh

    tester:
      build:
        image: ubuntu
      links:
        - restapiadapter
      environment:
        ADAPTER_HOST: restapiadapter
        ADAPTER_PORT: 8080

volumes:
  apistore:
