FROM node
MAINTAINER Tobias Freundorfer, https://github.com/tfreundo

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

# Install swagger project globally
RUN npm install -g swagger

# Add user
RUN useradd -ms /bin/bash swagger

USER swagger
WORKDIR /home/swagger

# Clone APIAdapter repo
RUN git clone -b dev-swagger https://github.com/tfreundo/gRPC-APIAdapter.git

# Install all necessary modules using npm
RUN export NODE_PATH=$NODEPATH:/home/swagger/gRPC-APIAdapter/rest-apiadapter
WORKDIR /home/swagger/gRPC-APIAdapter/rest-apiadapter
RUN npm install

# Start the adapter
RUN sh startRESTApi.sh
