version: '2'
services:

  testgrpcserver:
    build:
      context: .
      dockerfile: Dockerfile-testgrpcserver
    ports:
      - "8181"
    environment:
      LISTEN_PORT: 8181
    volumes:
      - /api
    command: node testgrpcserver.js

  restapiadapter:
    build:
      context: .
      dockerfile: Dockerfile-restapiadapter
    volumes_from:
      - testgrpcserver
    links:
      - testgrpcserver
    ports:
      - "10010"
    environment:
      API_HOST: testgrpcserver
      API_PORT: 8181
      API_PROTO_PATH: "/api/main.proto"
      REST_LISTEN_PORT: 10010
    command: sh startRESTApi.sh

  tester:
    build:
      context: .
      dockerfile: Dockerfile-tester
    links:
      - restapiadapter
    environment:
      ADAPTER_HOST: restapiadapter
      ADAPTER_PORT: 10010
    command: sh startTestClient.sh
