swagger: "2.0"
info:
 version: "1.0"
 title: gRPC-API-Adapter (REST)
host: localhost:10010
basePath: /
schemes:
 - http
 - https
consumes:
 - application/json
produces:
 - application/json
paths:
 /getServiceRequest:
  x-swagger-router-controller: getSerReq
  get:
    parameters:
     - name: id
       in: query
       description: The ServiceRequestId to query for.
       type: string
    description: Gets information for the specified ServiceRequestId.
    operationId: getSerReq
    produces:
     - application/json
    responses:
     200:
      description: Success
      schema:
       $ref: "#/definitions/ServiceRequestInfo"

     default:
      description: Error
      schema:
       $ref: "#/definitions/ErrorResponse"
 /TesterService/NoStream:
  x-swagger-router-controller: gen_TesterService
  post:
   parameters:
    - name: CalculationRequest
      in: body
      required: true
      schema:
       $ref: "#/definitions/CalculationRequest"
   description: gRPC-Service NoStream
   operationId: NoStream
   consumes:
    - application/json
   produces:
    - application/json
   responses:
    200:
     description: Success
     schema:
      $ref: "#/definitions/ServiceRequestResponse"
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /TesterService/RequestStream:
  x-swagger-router-controller: gen_TesterService
  post:
   parameters:
    - name: id
      in: query
      description: The ServiceRequestId to query for.
      type: string
    - name: AddUserRequest
      in: body
      required: true
      schema:
       $ref: "#/definitions/AddUserRequest"
   description: gRPC-Service RequestStream
   operationId: RequestStream
   consumes:
    - application/json
   produces:
    - application/json
   responses:
    200:
     description: Success
     schema:
      $ref: "#/definitions/ServiceRequestResponse"
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /TesterService/RequestStream/OpenStream:
  x-swagger-router-controller: gen_TesterService
  post:
   description: Opens a Stream for gRPC-Service RequestStream
   operationId: RequestStreamOpenStream
   produces:
    - application/json
   responses:
    200:
     description: Success
     schema:
      $ref: "#/definitions/ServiceRequestResponse"

    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /TesterService/RequestStream/CloseStream:
  x-swagger-router-controller: gen_TesterService
  delete:
   parameters:
    - name: id
      in: query
      description: The StreamId to delete.
      type: string
   description: Deletes/closes a given Stream for gRPC-Service RequestStream
   operationId: RequestStreamCloseStream
   produces:
    - text/plain
   responses:
    200:
     description: Success
     schema:
      title: RequestStreamCloseStreamResponse
      type: string
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /TesterService/ResponseStream:
  x-swagger-router-controller: gen_TesterService
  post:
   parameters:
    - name: ListUsersRequest
      in: body
      required: true
      schema:
       $ref: "#/definitions/ListUsersRequest"
   description: gRPC-Service ResponseStream
   operationId: ResponseStream
   consumes:
    - application/json
   produces:
    - application/json
   responses:
    200:
     description: Success
     schema:
      $ref: "#/definitions/ServiceRequestResponse"
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /TesterService/BidirectionalStream:
  x-swagger-router-controller: gen_TesterService
  post:
   parameters:
    - name: id
      in: query
      description: The ServiceRequestId to query for.
      type: string
    - name: GreetingRequest
      in: body
      required: true
      schema:
       $ref: "#/definitions/GreetingRequest"
   description: gRPC-Service BidirectionalStream
   operationId: BidirectionalStream
   consumes:
    - application/json
   produces:
    - application/json
   responses:
    200:
     description: Success
     schema:
      $ref: "#/definitions/ServiceRequestResponse"
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /TesterService/BidirectionalStream/OpenStream:
  x-swagger-router-controller: gen_TesterService
  post:
   description: Opens a Stream for gRPC-Service BidirectionalStream
   operationId: BidirectionalStreamOpenStream
   produces:
    - application/json
   responses:
    200:
     description: Success
     schema:
      $ref: "#/definitions/ServiceRequestResponse"

    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /TesterService/BidirectionalStream/CloseStream:
  x-swagger-router-controller: gen_TesterService
  delete:
   parameters:
    - name: id
      in: query
      description: The StreamId to delete.
      type: string
   description: Deletes/closes a given Stream for gRPC-Service BidirectionalStream
   operationId: BidirectionalStreamCloseStream
   produces:
    - text/plain
   responses:
    200:
     description: Success
     schema:
      title: BidirectionalStreamCloseStreamResponse
      type: string
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /swagger:
  x-swagger-pipe: swagger_raw
definitions:
 ErrorResponse:
  required:
   - message
  properties:
   message:
    type: string
 ServiceRequestResponse:
  required:
   - requestId
  properties:
   requestId:
    type: string
   streamId:
    type: string
 innerinnerMsg:
  properties:
   testinfo:
    type: string
 ServiceRequestInfo:
  properties:
    status:
      type: string
    service:
      type: string
    output:
      type: object   
 innerMsg:
  properties:
   info:
    type: string
   bla:
    $ref: "#/definitions/innerinnerMsg"
 CalculationRequest:
  properties:
   values_to_use:
    type: array
    items:
     type: integer
   type:
    $ref: "#/definitions/CalculationEnum"
   info:
    $ref: "#/definitions/innerMsg"
 CalculationResult:
  properties:
   map:
    type: array
    items:
     type: integer
 User:
  properties:
   firstname:
    type: string
   lastname:
    type: string
 AddUserRequest:
  properties:
   firstname:
    type: string
   lastname:
    type: string
 UserQtyResponse:
  properties:
   qty:
    type: integer
 ListUsersRequest:
  properties:
   limit:
    type: integer
 UserResponse:
  properties:
   user:
    $ref: "#/definitions/User"
 GreetingRequest:
  properties:
   name:
    type: string
 GreetingResponse:
  properties:
   greeting:
    type: string
 CalculationEnum:
  type: string
  enum: ["UNKNOWN","ADDITION","MULTIPLICATION"]
