swagger: "2.0"
info:
 version: "1.0"
 title: gRPC-API-Adapter (REST)
host: localhost:10010
basePath: /
schemes:
 - http
 - https
consumes:
 - application/json
produces:
 - application/json
paths:
 /getServiceRequest:
  x-swagger-router-controller: getSerReq
  get:
    parameters:
     - name: id
       in: query
       description: The ServiceRequestId to query for.
       type: string
    description: Gets information for the specified ServiceRequestId.
    operationId: getSerReq
    produces:
     - text/plain
    responses:
     200:
      description: Success
      schema:
       title: ServiceRequest
       type: string
     default:
      description: Error
      schema:
       $ref: "#/definitions/ErrorResponse"
 /Ec2Ops/createVm:
  x-swagger-router-controller: Ec2Ops
  post:
   parameters:
    - name: CreateVmRequest
      in: body
      required: true
      schema:
       type: object
   description: gRPC-Servive for createVm
   operationId: createVm
   consumes:
    - application/json
   produces:
    - text/plain
   responses:
    200:
     description: Success
     schema:
      title: createVmRequestId
      type: string
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /Ec2Ops/destroyVm:
  x-swagger-router-controller: Ec2Ops
  post:
   parameters:
    - name: DestroyVmRequest
      in: body
      required: true
      schema:
       type: object
   description: gRPC-Servive for destroyVm
   operationId: destroyVm
   consumes:
    - application/json
   produces:
    - text/plain
   responses:
    200:
     description: Success
     schema:
      title: destroyVmRequestId
      type: string
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /Ec2Ops/initChefRepo:
  x-swagger-router-controller: Ec2Ops
  post:
   parameters:
    - name: InitChefRepoRequest
      in: body
      required: true
      schema:
       type: object
   description: gRPC-Servive for initChefRepo
   operationId: initChefRepo
   consumes:
    - application/json
   produces:
    - text/plain
   responses:
    200:
     description: Success
     schema:
      title: initChefRepoRequestId
      type: string
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /WordPressOps/deployWpApp:
  x-swagger-router-controller: WordPressOps
  post:
   parameters:
    - name: DeployWpAppRequest
      in: body
      required: true
      schema:
       type: object
   description: gRPC-Servive for deployWpApp
   operationId: deployWpApp
   consumes:
    - application/json
   produces:
    - text/plain
   responses:
    200:
     description: Success
     schema:
      title: deployWpAppRequestId
      type: string
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /WordPressOps/deployDb:
  x-swagger-router-controller: WordPressOps
  post:
   parameters:
    - name: DeployDbRequest
      in: body
      required: true
      schema:
       type: object
   description: gRPC-Servive for deployDb
   operationId: deployDb
   consumes:
    - application/json
   produces:
    - text/plain
   responses:
    200:
     description: Success
     schema:
      title: deployDbRequestId
      type: string
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /WordPressOps/backupDb:
  x-swagger-router-controller: WordPressOps
  post:
   parameters:
    - name: BackupDbRequest
      in: body
      required: true
      schema:
       type: object
   description: gRPC-Servive for backupDb
   operationId: backupDb
   consumes:
    - application/json
   produces:
    - text/plain
   responses:
    200:
     description: Success
     schema:
      title: backupDbRequestId
      type: string
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /WordPressOps/restoreDb:
  x-swagger-router-controller: WordPressOps
  post:
   parameters:
    - name: RestoreDbRequest
      in: body
      required: true
      schema:
       type: object
   description: gRPC-Servive for restoreDb
   operationId: restoreDb
   consumes:
    - application/json
   produces:
    - text/plain
   responses:
    200:
     description: Success
     schema:
      title: restoreDbRequestId
      type: string
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /GenericOps/executeCookbook:
  x-swagger-router-controller: GenericOps
  post:
   parameters:
    - name: ExecuteCookbookRequest
      in: body
      required: true
      schema:
       type: object
   description: gRPC-Servive for executeCookbook
   operationId: executeCookbook
   consumes:
    - application/json
   produces:
    - text/plain
   responses:
    200:
     description: Success
     schema:
      title: executeCookbookRequestId
      type: string
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /swagger:
  x-swagger-pipe: swagger_raw
definitions:
 ErrorResponse:
  required:
   - message
  properties:
   message:
    type: string
