swagger: "2.0"
info:
 version: "1.0"
 title: gRPC-API-Adapter (REST)
host: localhost:10010
basePath: /
schemes:
 - http
 - https
consumes:
 - application/json
produces:
 - application/json
paths:
 /getServiceRequest:
  x-swagger-router-controller: getSerReq
  get:
    parameters:
     - name: id
       in: query
       description: The ServiceRequestId to query for.
       type: string
    description: Gets information for the specified ServiceRequestId.
    operationId: getSerReq
    produces:
     - text/plain
    responses:
     200:
      description: Success
      schema:
       title: ServiceRequest
       type: string
     default:
      description: Error
      schema:
       $ref: "#/definitions/ErrorResponse"
 /Ec2Ops/createVm:
  x-swagger-router-controller: gen_Ec2Ops
  post:
   parameters:
    - name: CreateVmRequest
      in: body
      required: true
      schema:
       $ref: "#/definitions/CreateVmRequest"
   description: gRPC-Servive for createVm
   operationId: createVm
   consumes:
    - application/json
   produces:
    - text/plain
   responses:
    200:
     description: Success
     schema:
      title: createVmRequestId
      type: string
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /Ec2Ops/destroyVm:
  x-swagger-router-controller: gen_Ec2Ops
  post:
   parameters:
    - name: DestroyVmRequest
      in: body
      required: true
      schema:
       $ref: "#/definitions/DestroyVmRequest"
   description: gRPC-Servive for destroyVm
   operationId: destroyVm
   consumes:
    - application/json
   produces:
    - text/plain
   responses:
    200:
     description: Success
     schema:
      title: destroyVmRequestId
      type: string
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /Ec2Ops/initChefRepo:
  x-swagger-router-controller: gen_Ec2Ops
  post:
   parameters:
    - name: InitChefRepoRequest
      in: body
      required: true
      schema:
       $ref: "#/definitions/InitChefRepoRequest"
   description: gRPC-Servive for initChefRepo
   operationId: initChefRepo
   consumes:
    - application/json
   produces:
    - text/plain
   responses:
    200:
     description: Success
     schema:
      title: initChefRepoRequestId
      type: string
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /WordPressOps/deployWpApp:
  x-swagger-router-controller: gen_WordPressOps
  post:
   parameters:
    - name: DeployWpAppRequest
      in: body
      required: true
      schema:
       $ref: "#/definitions/DeployWpAppRequest"
   description: gRPC-Servive for deployWpApp
   operationId: deployWpApp
   consumes:
    - application/json
   produces:
    - text/plain
   responses:
    200:
     description: Success
     schema:
      title: deployWpAppRequestId
      type: string
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /WordPressOps/deployDb:
  x-swagger-router-controller: gen_WordPressOps
  post:
   parameters:
    - name: DeployDbRequest
      in: body
      required: true
      schema:
       $ref: "#/definitions/DeployDbRequest"
   description: gRPC-Servive for deployDb
   operationId: deployDb
   consumes:
    - application/json
   produces:
    - text/plain
   responses:
    200:
     description: Success
     schema:
      title: deployDbRequestId
      type: string
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /WordPressOps/backupDb:
  x-swagger-router-controller: gen_WordPressOps
  post:
   parameters:
    - name: BackupDbRequest
      in: body
      required: true
      schema:
       $ref: "#/definitions/BackupDbRequest"
   description: gRPC-Servive for backupDb
   operationId: backupDb
   consumes:
    - application/json
   produces:
    - text/plain
   responses:
    200:
     description: Success
     schema:
      title: backupDbRequestId
      type: string
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /WordPressOps/restoreDb:
  x-swagger-router-controller: gen_WordPressOps
  post:
   parameters:
    - name: RestoreDbRequest
      in: body
      required: true
      schema:
       $ref: "#/definitions/RestoreDbRequest"
   description: gRPC-Servive for restoreDb
   operationId: restoreDb
   consumes:
    - application/json
   produces:
    - text/plain
   responses:
    200:
     description: Success
     schema:
      title: restoreDbRequestId
      type: string
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /GenericOps/executeCookbook:
  x-swagger-router-controller: gen_GenericOps
  post:
   parameters:
    - name: ExecuteCookbookRequest
      in: body
      required: true
      schema:
       $ref: "#/definitions/ExecuteCookbookRequest"
   description: gRPC-Servive for executeCookbook
   operationId: executeCookbook
   consumes:
    - application/json
   produces:
    - text/plain
   responses:
    200:
     description: Success
     schema:
      title: executeCookbookRequestId
      type: string
    default:
     description: Error
     schema:
      $ref: "#/definitions/ErrorResponse"
 /swagger:
  x-swagger-pipe: swagger_raw
definitions:
 ErrorResponse:
  required:
   - message
  properties:
   message:
    type: string
 AwsInstanceId:
  properties:
   id:
    type: string
 CreateVmRequest:
  properties:
   name:
    type: string
   tag:
    type: string
   region:
    type: string
   imageId:
    type: string
   username:
    type: string
   instanceType:
    type: string
   securityGroupIds:
    type: string
 InitChefRepoRequest:
  properties:
   credentials:
    $ref: "#/definitions/SshCredentials"
 DestroyVmRequest:
  properties:
   instanceId:
    $ref: "#/definitions/AwsInstanceId"
   region:
    type: string
 SshCredentials:
  properties:
   username:
    type: string
   host:
    type: string
   keyfilename:
    type: string
   timeout:
    type: integer
 DeployWpAppRequest:
  properties:
   credentials:
    $ref: "#/definitions/SshCredentials"
   serverName:
    type: string
   port:
    type: string
   dbName:
    type: string
   dbHost:
    type: string
   dbPort:
    type: string
   dbUserName:
    type: string
   dbUserPassword:
    type: string
   dbRootPassword:
    type: string
   wpConfigOptions:
    type: string
 DeployDbRequest:
  properties:
   credentials:
    $ref: "#/definitions/SshCredentials"
   serviceName:
    type: string
   port:
    type: integer
   username:
    type: string
   userPassword:
    type: string
   dbName:
    type: string
   rootPassword:
    type: string
 BackupDbRequest:
  properties:
   credentials:
    $ref: "#/definitions/SshCredentials"
   serviceName:
    type: string
   dbUsername:
    type: string
   dbUserPassword:
    type: string
   dbName:
    type: string
   backupFilename:
    type: string
 RestoreDbRequest:
  properties:
   credentials:
    $ref: "#/definitions/SshCredentials"
   serviceName:
    type: string
   dbUsername:
    type: string
   dbUserPassword:
    type: string
   dbName:
    type: string
   backupFilename:
    type: string
 ExecuteCookbookRequest:
  properties:
   credentials:
    $ref: "#/definitions/SshCredentials"
   cookbookName:
    type: string
   recipeName:
    type: string
   attributesKeys:
    type: string
   attributesValues:
    type: string
 CreateVmResponse:
  properties:
   instanceId:
    $ref: "#/definitions/AwsInstanceId"
   publicDns:
    type: string
   outputLog:
    type: string
 DestroyVmResponse:
  properties:
   outputLog:
    type: string
 InitChefRepoResponse:
  properties:
   outputLog:
    type: string
 DeployWpAppResponse:
  properties:
   outputLog:
    type: string
 DeployDbResponse:
  properties:
   outputLog:
    type: string
 BackupDbResponse:
  properties:
   outputLog:
    type: string
 RestoreDbResponse:
  properties:
   outputLog:
    type: string
 ExecuteCookbookResponse:
  properties:
   outputLog:
    type: string
